on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/known_hosts
          ssh-keyscan -H "${{secrets.SSH_HOST}}" > ~/.ssh/known_hosts
      - name: connect, pull and build
        run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd ${{secrets.WORK_DIR}} && git checkout ${{secrets.MAIN_BRANCH}} && git pull && npm run build"
      - name: cleanup
        run: rm -rf ~/.ssh
      
